spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  application:
    name: limorent-backend

server:
  port: ${SERVER_PORT:8080}

springdoc:
  swagger-ui:
    path: /swagger-ui.html